name: reboostrap-loong64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 20 * * *'

  workflow_dispatch:
  
env:
  USE_MIRROR: https://mirror.sjtu.edu.cn/debian/

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    strategy:
      fail-fast: false
      matrix:
        ver: [12, 13]
    steps:
      - name: Install deps
        run: echo "Skip"
        #sudo apt update && sudo apt install -y pbuilder git debian-archive-keyring debian-keyring

      - name: Clone reboostrap
        run: rm -rf rebootstrap && git clone https://salsa.debian.org/Revy/rebootstrap.git

      - name: Create base for reboostrap
        run: echo "Skip"
        #sudo pbuilder create --distribution sid --mirror $USE_MIRROR

      - name: reboostrap for loong64
        run: sudo pbuilder --execute rebootstrap/bootstrap.sh HOST_ARCH=loong64 GCC_VER=${{ matrix.ver }} MIRROR=$USE_MIRROR 2>&1 | tee build-${{ matrix.ver }}.log
        
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: build-log-${{ matrix.ver }}
          path: build-${{ matrix.ver }}.log
          if-no-files-found: error
